import type { Metadata } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App2222222222",
  description: "Generated by create next app12222",
};

export default function SubMainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div>서브메인 헤더1</div>
      {children}
      <div>서브메인 푸터1</div>
    </>
  );
}
